-- REVISED loader: ensures canonical_manufacturers include ALL good_mids (from aliases and names)
BEGIN;

-- 1) Canonical manufacturers (good_mid + optional name)
WITH canon(good_mid, manufacturer_name) AS (
  VALUES
      ('CNDONSHA800DON', 'Dongguan Shanjia Clothing Co., Ltd.'),
      ('CNQIAECO2JIN', 'Yiwu Qiangkuang Ecommerce Store (Individual Business)'),
      ('CNCHECHUBAO', 'Baoding Chenchuang Trading Co., Ltd.'),
      ('CNTAIINDTAI', 'Taizhou Borui Industry and Trade Co., Ltd.'),
      ('CNZHUJIU99SHA', 'Zhuji Jiuzhi Textile Factory'),
      ('CNSUZTIA4555SUZ', 'Suzhou Tianbianyou Culture Media Co., Ltd.'),
      ('CNBAINEW857BAO', ''),
      ('CNGAOXIN9902BAO', ''),
      ('CNFOSFEI302FOS', ''),
      ('CNBAINEW9906BAO', ''),
      ('CNGAONEW9904BAO', ''),
      ('CNBAOBOP132BAO', ''),
      ('CNFOSANY9903FOS', ''),
      ('CNHANYIF603HAN', ''),
      ('CNHUBSHU21TIA', ''),
      ('CNXINZUL1819XIN', 'Xinyu Zulu Shoes Co., Ltd.'),
      ('CNHONBEI3FOS', ''),
      ('CNDONMAO93JIN', ''),
      ('CNDAQZHA3DAQ', ''),
      ('CNGUAYUX9906GUA', ''),
      ('CNBAOSHU5BAO', ''),
      ('CNGAOXIN421BAO', ''),
      ('CNGAOXIN3071BAO', ''),
      ('CNHAIMEI118HAI', ''),
      ('CNHEJIA19JIN', ''),
      ('CNGAOXIN623BAO', ''),
      ('CNBEIHEN4YUL', ''),
      ('CNGUAHEL521GUA', ''),
      ('CNYIWKUN704JIN', ''),
      ('CNFOSKAQ48FOS', ''),
      ('CNZHEOST403ZHE', ''),
      ('CNGUAFUH9GUA', ''),
      ('CNYUECOU4ANQ', ''),
      ('CNSHEQIN984SHE', ''),
      ('CNBAOCHE99BAO', ''),
      ('CNXIASUP89ZHU', ''),
      ('CNYUAHOM68SUI', ''),
      ('CNYIWQIS1666JIN', ''),
      ('CNZHEAIY9900JIN', ''),
      ('CNYUEREM9ANQ', ''),
      ('CNKUADEP511FOS', ''),
      ('CNBAINEW787BAO', ''),
      ('CNGAOXIN419BAO', ''),
      ('CNWUHXIX32WUH', ''),
      ('CNBAONUO7BAO', ''),
      ('CNJUNINC2LIS', ''),
      ('CNZHAXIA1542ZHA', ''),
      ('CNGUASHU408GUA', ''),
      ('CNQINCIT3014QIN', ''),
      ('CNFOSCOL553FOS', ''),
      ('CNNANYAQ3NAN', ''),
      ('CNGUAMIM67GUA', ''),
      ('CNQINSHO421QUA', ''),
      ('CNHUAMEI21GUA', ''),
      ('CNJIULIT1092JIU', ''),
      ('CNDONCHI401JIN', ''),
      ('CNGAOCIT9901BAO', ''),
      ('CNGUASEA245GUA', ''),
      ('CNGUAZHI995GUA', ''),
      ('CNJIAWEN215HAN', ''),
      ('CNBAOMEI328BAO', ''),
      ('CNGUASIN27GUA', ''),
      ('CNDONZHU93JIN', ''),
      ('CNZHECAI13ZHE', ''),
      ('CNGAOWEI233BAO', ''),
      ('CNBAOHOU1BAO', ''),
      ('CNXIAECO28FOS', ''),
      ('CNGUABOP9915GUA', ''),
      ('CNGUAXIO929GUA', ''),
      ('CNFOSBEI708FOS', ''),
      ('CNYANJIN8XUC', ''),
      ('CNHUASHE589HUA', ''),
      ('CNYIWKOU1611JIN', ''),
      ('CNYUECOU83ANQ', ''),
      ('CNYIWQIA613JIN', ''),
      ('CNGAOXIN6081BAO', ''),
      ('CNWUHBOY167WUH', ''),
      ('CNYIWJIN4348JIN', ''),
      ('CNFOSJIA9902FOS', ''),
      ('CNUSCCRO518JIN', ''),
      ('CNGAOXIN402BAO', ''),
      ('CNLEIDIG46SHE', ''),
      ('CNGUAWEI434GUA', ''),
      ('CNGONXIN64JIU', ''),
      ('CNGAOXIN101BAO', ''),
      ('CNGAOYUE301BAO', ''),
      ('CNGUADAN194GUA', ''),
      ('CNBAODAL108BAO', ''),
      ('CNYINDEP17FOS', ''),
      ('CNANQYIH83ANQ', ''),
      ('CNMINCOU1018SHA', ''),
      ('CNGAOLIA3160BAO', ''),
      ('CNHENBUF592ZHE', ''),
      ('CNSHASEN462SHA', ''),
      ('CNCHAWAN42CHA', ''),
      ('CNDABDEP26ZHE', ''),
      ('CNGAOXIN223BAO', ''),
      ('CNGUAGUL334GUA', ''),
      ('CNFOSYIR130FOS', ''),
      ('CNTAIJUY32TAI', ''),
      ('CNYIWKAN655JIN', ''),
      ('CNYIWWOY6JIN', ''),
      ('CNYIWMAG27JIN', ''),
      ('CNNANXUZ178NAN', ''),
      ('CNZHUHAO151SHA', ''),
      ('CNQITYUN23QIT', ''),
      ('CNSHIQIA99SHI', ''),
      ('CNSHE9910JIN', ''),
      ('CNYIWTUA994JIN', ''),
      ('CNYIWXUG9JIN', ''),
      ('CNFOSBEI9901FOS', ''),
      ('CNDONBUG7JIN', ''),
      ('CNBAINEW733BAO', ''),
      ('CNBAINEW351BAO', ''),
      ('CNGUALIH287GUA', ''),
      ('CNYIWCOO157JIN', ''),
      ('CNGAOXIN531BAO', ''),
      ('CNHEFDIE1188HEF', ''),
      ('VNBINBGBAC', 'AN BINH BG GARMENT COMPANY LIMITED'),
      ('CNNANMEI99QUA', ''),
      ('CNGUAYIB196GUA', ''),
      ('CNWENNIS9938WEN', ''),
      ('CNYIWAIX9930JIN', ''),
      ('HKHONKON98YAU', ''),
      ('CNZHOHAN19ZHO', ''),
      ('CNGUAYUQ23GUA', ''),
      ('CNWANHAN7CHA', ''),
      ('CNYIWSHI2120JIN', ''),
      ('CNGUARUN353GUA', ''),
      ('CNJINCOM341BAO', ''),
      ('CNFOSAIR3FOS', ''),
      ('CNYIWJUC874JIN', ''),
      ('CNYIWCHO555JIN', ''),
      ('CNWUJLIX5SUZ', ''),
      ('CNHEFXIN1223HEF', ''),
      ('HKSUNCOKWU', ''),
      ('CNMENSEL6HAI', ''),
      ('CNXIAMIS7ZHO', ''),
      ('CNYIWHEQ8JIN', ''),
      ('CNXIXNEW2062XIA', ''),
      ('VNMINVIE2845HAI', ''),
      ('VNHUNFUN24DAK', 'HUNG FUNG GARMENT (VIETNAM) CO., LTD'),
      ('CNBAINEW1BAO', ''),
      ('CNYIWRON399JIN', ''),
      ('CNDONFUYJIN', ''),
      ('CNFOSQIJ6FOS', ''),
      ('CNDONDUR5JIN', ''),
      ('CNGAOXIN427BAO', ''),
      ('CNYIWJIX715JIN', ''),
      ('CNSUZFUM9SUZ', ''),
      ('CNNANGAL479NAN', ''),
      ('CNZHEZHE92ZHE', ''),
      ('CNYIDPIN3YIC', ''),
      ('CNGUAMAN680GUA', ''),
      ('CNGUASHE611GUA', ''),
      ('CNGUAXIK238GUA', ''),
      ('CNSHICOU15CHI', ''),
      ('CNDONDIS8KUN', ''),
      ('CNGAOLIA7205BAO', ''),
      ('CNDONMOU30JIN', ''),
      ('CNSHESHE18SHE', ''),
      ('CNHECART1418HAN', ''),
      ('CNBAOCHE6BAO', 'YIWU XINMAN JEWELRY CO. LTD'),
      ('CNMEEBEA61FUZ', ''),
      ('CNSHEMIL847SHE', ''),
      ('CNGUAOMA123GUA', ''),
      ('CNYIWNIT8JIN', ''),
      ('CNYIWKEZ3JIN', ''),
      ('CNQINLAK888NAN', ''),
      ('CNSHAQIN2816SHA', ''),
      ('CNHANHOU308HAN', ''),
      ('CNSHEQUZ273SHE', ''),
      ('CNLIN3831JIN', ''),
      ('CNXIUCOU154JIU', ''),
      ('CNYUEREH9ANQ', ''),
      ('CNHANMIT1399HAN', ''),
      ('CNGAOXIN327BAO', ''),
      ('CNYIWLAI5JIN', ''),
      ('CNYIWFUW18JIN', ''),
      ('CNBAOVAL7BAO', ''),
      ('CNYIWXID788JIN', ''),
      ('CNSHETRA8GUA', ''),
      ('CNJIADIA326NAN', ''),
      ('CNMIACOU9HAN', ''),
      ('CNFUZGUL18FUZ', ''),
      ('CNHANYUH1399HAN', ''),
      ('CNBAIXIN8BAO', ''),
      ('CNXINTEX70QIN', ''),
      ('CNYIWDUC9JIN', ''),
      ('CNYIWPUY8JIN', ''),
      ('CNPUJJIA19JIN', ''),
      ('CNYIWNIA14JIN', ''),
      ('CNGUIBAO29GUI', ''),
      ('CNZHEGUA329ZHE', ''),
      ('CNWUHNEW58WUH', ''),
      ('CNGUALON665GUA', ''),
      ('CNZHEMOY7ZHE', ''),
      ('CNTIACHA402TIA', ''),
      ('CNBAOBAI1BAO', ''),
      ('CNTIAZHE116TIA', ''),
      ('CNTAIBOR1TAI', ''),
      ('CNZHUYIS772SHA', ''),
      ('CNSHEULU7012SHE', ''),
      ('CNSHALAN170SHA', ''),
      ('CNNANHAO3399NAN', ''),
      ('CNDONSHI101DON', ''),
      ('CNBAINEW28BAO', ''),
      ('CNSUZIND199SUZ', ''),
      ('CNGUAMUY328GUA', ''),
      ('CNZHAZHE1212JIN', ''),
      ('CNSUSHUI15HUI', ''),
      ('CNYIWSU508JIN', ''),
      ('CNJINHUI3QUA', ''),
      ('CNGAOXIN1411BAO', ''),
      ('CNFOSDEC38FOS', ''),
      ('CNCENWEI2WUZ', ''),
      ('CNDONYIT5JIN', ''),
      ('CNZHUYUA216ZHU', ''),
      ('CNSHEKAI12SHE', ''),
      ('CNSHEXIN53SHE', ''),
      ('CNGUAXIJ278GUA', ''),
      ('CNGUAQIA222GUA', ''),
      ('CNWUHWEI58WUH', ''),
      ('CNYUNTRA12FOS', ''),
      ('CNFOSANN8FOS', ''),
      ('CNFOSSUM4FOS', ''),
      ('CNLEFDEP23LUO', ''),
      ('CNDONJUN116JIN', ''),
      ('CNGUASHI445GUA', ''),
      ('CNWUHYOU77WUH', ''),
      ('CNSHEMAI375SHE', ''),
      ('CNYIWPUM36JIN', ''),
      ('CNYIWBOD5JIN', ''),
      ('CNPUJQIA7JIN', ''),
      ('CNBEIMIN319BEI', ''),
      ('CNWUHDON450WUH', ''),
      ('CNGUAYIN680GUA', ''),
      ('CNYIWLUS715JIN', ''),
      ('CNYIWINT3JIN', ''),
      ('CNYIWGAI9JIN', ''),
      ('CNXIAYIR159XIA', ''),
      ('CNBAOHUI209BAO', ''),
      ('CNBAOBAI60BAO', ''),
      ('CNPUJTUO371JIN', ''),
      ('CNTOUTRA302JIN', ''),
      ('CNYIWKUO606JIN', ''),
      ('CNYIWXUA405JIN', ''),
      ('CNSHUCOU20SUQ', ''),
      ('CNYIWNAN931JIN', ''),
      ('CNCHAWAN8006CHA', ''),
      ('CNDINSUP8GUA', ''),
      ('CNGAOXIN403BAO', ''),
      ('CNYIWFUX8JIN', ''),
      ('CNYIWFUX9JIN', ''),
      ('CNHEBQIB4HEB', ''),
      ('CNZHEZHU52ZHE', ''),
      ('CNSHIHUI500QUA', ''),
      ('CNPOYCOU69SHA', ''),
      ('CNGUAYA503GUA', ''),
      ('TRTEKTEK72IST', ''),
      ('CNTIAHUA6TIA', ''),
      ('CNDONMAN409DON', ''),
      ('CNGUAXUA106GUA', ''),
      ('CNGUAYIS103GUA', ''),
      ('CNXINCHE2188HUL', ''),
      ('CNSHEDEP468EZH', ''),
      ('CNYIWBIN4417JIN', ''),
      ('CNYIWPAS33JIN', ''),
      ('CNSUZYIW995SUZ', ''),
      ('CNGUAYIH18LIA', ''),
      ('CNYIWFUX715JIN', ''),
      ('CNYIWENR9JIN', ''),
      ('CNNANLUO48NAN', ''),
      ('CNFOSCOO8FOS', ''),
      ('CNFOSYAD4FOS', ''),
      ('CNSHEBEA8FOS', ''),
      ('CNGUABAN806DON', ''),
      ('CNSHIWAL237QUA', ''),
      ('CNQINDIS3NAN', ''),
      ('CNGUAYAO211GUA', ''),
      ('CNYIWZIL718JIN', ''),
      ('CNSHAYIQ11RIZ', ''),
      ('CNGUANUA7GUA', ''),
      ('CNYIWBET4JIN', ''),
      ('CNBAIXIN7BAO', ''),
      ('CNQINQIY3QIN', ''),
      ('CNXIACIT2010XIA', ''),
      ('CNGAOXIN4441BAO', ''),
      ('CNPUJZHE99JIN', ''),
      ('CNORCGAR302GUA', ''),
      ('CNSUZTAI9SUZ', ''),
      ('CNTAIYUN25TAI', ''),
      ('CNJINJIN5547JIN', 'Jinhua Jindong District Liju Ecommerce Firm'),
      ('CNGAN806GAN', 'GanZhouPanHongTechnology'),
      ('CNLINCOL1126ANY', 'LINZHOUJINPENGSHANGMAO CO..LTD.'),
      ('CNNO1BIN303JIN', 'NO.1177,BINHAI, LONGWAN, WENZHOU.'),
      ('CNXIN9104XIN', 'XINYUSHIXIANNVHUQUQIANHEBAIHUIZHIXIECHANG'),
      ('CNWENCO26WEN', 'Wenzhoushifengyiwujinzhipin Co., Ltd.'),
      ('CNXIN2100HUL', 'XINGCHENGHUIMEICLOTHINGMANUFACTURINGFACTORY'),
      ('CNFOSOLT1090FOS', 'FOSHANSHIMMUPINGFUSHI O..LTD.'),
      ('CNHAOCOL912TAI', 'Haomiao.electronic.commerce co.,ltd'),
      ('CNZHOCOL493GUA', 'ZHONGQINMAOYIGUANGZHOU CO..LTD'),
      ('CNGUA2330GUA', 'GUANGZHOUSHILINGLINGQIKEJIFAZHANCO.LTD.'),
      ('CNNO5PET5XIA', 'NO.5, PETROLEUM ROAD'),
      ('CNPUJMEM8282JIN', 'PUJIANG MEMORY TOY CO., LTD'),
      ('CNJINCOL360JIN', 'JINHUASHIQINRONGMAOYI CO.LTD'),
      ('CNANHHEY2105HEF', 'ANHUI HEYE NETWORK TECHNOLOGY CO., LTD'),
      ('CNSHE179SHE', 'SHENZHENJIAMIWANGLUOISHUCO..LTD'),
      ('CNSHE1353SHE', 'SHENZHENSHIANRUNTAIKEJICO.LTD.'),
      ('CNGUAAIC3183GUA', 'GUANGZHOU AICHUANGJINCHUKOUMAOYI CO., LTD.'),
      ('CNFUJCHE814FUZ', 'Fujian Chengrui Shoes Industry Co. , Ltd.'),
      ('CNPANJIN202JIN', 'PANAN JINGYA HORTICULTURAL SUPPLIES FACTORY'),
      ('CNHUACOL104BEN', 'HUAIYUANXINHAODIANZISHANGWU CO.LTD.'),
      ('CNGUA162JIE', 'GUANGZHOUTONGRUNTRADINGCO..LTD'),
      ('CNHUIWOM2282XIN', 'HUIYU WOMEN''S SHOE FACTORY'),
      ('CNFOSSHA2450FOS', 'Foshan Shanmu clothing Co., LTD'),
      ('CNHUIDUD234HUI', 'HUIZHOU DUDU PET PRODUCTS CO., ITD'),
      ('CNHENCIT153HEN', 'Hengyang City Coarse Tea and Rice Catering Culture Ltd'),
      ('CNJIN890JIN', 'JINHUAGUOYOUHOMEFURNISHINGCO.LTD'),
      ('CNTAICOL413TAI', 'TAIZHOUSHIDAHONGBAOGONGYIPIN CO.LTD.'),
      ('CNFOS2119FOS', 'Foshanshixuntuodianzico.Ltd'),
      ('CNYIW2310JIN', 'YIWUSHIYOUKEJINCHUKOUCO.LTD.'),
      ('CNGUA1076GUA', 'GUANGZHAUYUNNIFUSHICO.LTD.'),
      ('CNZHEMEN1188JIN', 'ZHEJIANG MENGDA IMPORT AND EXPORT CO., LTD.'),
      ('CNSHELTD238SHE', 'SHENZHENSHIDONGHEXINKEJI.CO,.LTD'),
      ('CNMOUCOU2744CHU', 'MOUDING COUNTY KUNI DEPARTMENT STORE SOLE PROPRIETORSHIP'),
      ('CNSHACOL1595RIZ', 'SHANDONGTAHAIWANGLUOKEJI CO.LTD.'),
      ('CNGUA850DON', 'GUANGZHOUHUIWANGDIANZISHANGWUCO..LTD'),
      ('CNKAIGARXIN', 'Xingcheng Kaisheng Garment Co., Ltd.'),
      ('CNXINKAI6543HUL', 'Xingcheng Kaiwei Garment Co., Ltd.'),
      ('CNKAIGARHUL', 'Xingcheng Kairuida Garment Co'),
      ('CNDONCOL364FUZ', 'DONGMING CO.LTD'),
      ('CNBAINEW297BAO', 'Baigou New Town Yaohuo Bags Factory (individual business owner)'),
      ('CNHUACHA570GUA', 'Huangshi Chaoju Clothing Store, Baiyun District, Guangzhou City'),
      ('CNMEIHESQUA', 'Nan''an Meishan Hesheng Knitting Factory'),
      ('CNBUYCLOSHA', 'Shantou Buyun Clothing Co., Ltd.'),
      ('CNDINFAS501DON', 'Dongguan Dingyangfeng Fashion Co., Ltd.'),
      ('CNXINKAI1HUL', 'Xingcheng Kairuida Garment Co., Ltd.'),
      ('CNYUEMEN46WEN', 'Yueqing Mengfu International Trade Co., Ltd.'),
      ('CNYIWYAQ205JIN', 'Yiwu Yaqin Electronic Commerce Company (individual business owner)'),
      ('CNYIWU146JIN', 'Yiwu Yaoer Ecommerce Co., Ltd.'),
      ('CNSHE85SHA', 'Shenzhen 85 WinWin Trading Co., Ltd.'),
      ('CNSHEZHE6SHE', 'Shenzhen Dechuang Photoelectric Technology Co., Ltd'),
      ('CNGUAZUO108GUA', 'Guangzhou Zuomu Trading Co., Ltd.'),
      ('CNGUAHUI302GUA', 'Guangzhou Huiya Garment Co., Ltd.'),
      ('CNZHUBAO164XUC', 'Changge City Zhubao General Store (Individual Business)'),
      ('CNPEISHA2263GUA', 'GUANGZHOUPEISHANFUZHUANGGONGYINGLIANGUANICO.LTD'),
      ('CNSHESENWEN', 'Wenzhoushensengongju Co., Ltd.'),
      ('CNGANTEC1026GAN', 'GanZhouPanHong Technology Co., LTD'),
      ('CNWENCO497WEN', 'Wenzhouyihewanjuzhizao Co., Ltd.'),
      ('CNGUACOL2202GUI', 'GUANGXIPINGNANXIANYUHANKEJI CO..LTD'),
      ('CNSHEBEA3241SHE', 'SHENZHEN BEAUTIFUL STORY TRADING CO., LTD.'),
      ('CNBANTOO463GUA', 'BANANA TOOTH CLOTHING CO.LTD'),
      ('CNSHE683SHE', 'SHENZHENJIECHANGSHENGINDUSTRIALCO..LTD'),
      ('CNSHE201SHE', 'SHENZHENTUOWEIDIANZISHANGWUCO.LTD.'),
      ('CNHESSUJWEN', 'Wenzhouheshengsujiao Co., Ltd.'),
      ('CNWENZHOWEN', 'Wenzhouchangchuangshangmao Co., Ltd.'),
      ('CNSHEPHO6SHE', 'ZHENGZHOUAMIERMAOYI CO.LTD'),
      ('CNLANSEA2236HUL', 'PUJIANGXIANFULIUMANMAOYICO.LTD.'),
      ('KHWANLY137PHN', 'Wan Ly (Cambodia) Garment Co., Ltd.'),
      ('KHLONCAMPHN', 'Lonso (Cambodia) Garment Co., Ltd.'),
      ('KHXUNINT32PHN', 'Xundu International Trading Company Limited'),
      ('VNTHAVANHAI', 'THAM VAN COMPANY LIMITED'),
      ('KHNEWJINPHN', 'New Jing Feng (Cambodia) Garment Co., Ltd.'),
      ('VNVIESHA2180BIN', 'Vietnam Shangya Company Limited'),
      ('VNMBVIE5817HOC', 'MB Vietnam Garment Production Trading Service Co., Ltd.'),
      ('VNGIAPHU30HOC', 'Gia Phuc Development Production Trading Service Co., Ltd.'),
      ('KHSANMATPHN', 'San Mateo Garment (Cambodia) Co., Ltd.'),
      ('VNDAIDUO43HAN', 'Dai Duong Hai Duong Company Limited'),
      ('VNYINGAR52BIN', 'YINIFU CLOTHING COMPANY LIMITED'),
      ('VNCHAHUN30HOC', 'Chan Hung Garment Import-Export Production Co., Ltd.'),
      ('VNYENGOL814HOC', 'YENI GOLDEN IMPORT EXPORT TRADING COMPANY LIMITED'),
      ('VNJOYVINHUN', 'Joy Vina Fashion Co., Ltd.'),
      ('KHYILAN18PHN', 'Yi Lan Ji Garment (Cambodia) Co., Ltd.'),
      ('VNCHAHUN1826HOC', 'CHAN HUNG IMPORT EXPORT GARMENT PRODUCTION COMPANY LIMITED'),
      ('KHXIYVIE1206PHN', 'XIYIN VIETNAM DISTRIBUTION COMPANY LIMITED'),
      ('VNSAIGAR464HOC', 'Saigon Garments Co., Ltd.'),
      ('KHCAMFORPHN', 'Cam Forever Co., Ltd.'),
      ('VNDUYMIN28HOC', 'Duy Minh Phat Trading Production Garment Import Export Co., Ltd.'),
      ('KHRUIWEN27PHN', 'Rui Wen Aries (Cambodia) Garments Co., Ltd.'),
      ('VNCHUGAR1THA', 'KHOI NGHIEP GARMENT COMPANY LIMITED'),
      ('KHJOYRIC6KAM', 'Joy Rich Garment (Cambodia) Co., Ltd.'),
      ('VNTANHAI3904HOC', 'Tan Hai Sinh'),
      ('VNDAIMA24THA', 'Dai Ma Garment Import-Export Company Limited'),
      ('KHNEWERA21PHN', 'New Era (Cambodia) Cashmere Textile Co., Ltd.'),
      ('KHSIXINKAN', 'Si Xin Underwear Factory'),
      ('VNSHAVIE2180BIN', 'Shangya Vietnam Co., Ltd.'),
      ('VNTHIHUN225HOC', 'Thien Hung Phat Factory'),
      ('VNTHIPHO475HOC', 'Thinh Phong Fashion Company Limited'),
      ('KHHONGAR34KAN', 'Hongruida Garment (Cambodia) Co., Ltd.'),
      ('VNTRUPHAHAN', 'Truong Phat Hanoi Production and Trading Company Limited'),
      ('VNCAOLON3HOC', 'CAO LONG PRODUCTION AND TRADING COMPANY LIMITED'),
      ('KHBLUVIS789PHN', 'BLUE VISTA CO.,LTD.'),
      ('KHCHICAMPHN', 'Chicbuck (Cambodia) Garments Manufacturing Co., Ltd.'),
      ('KHACTSEA130PHN', 'Active Seamless (Cambodia) Co.,LTD'),
      ('KHGRAINDPHN', 'Grandfield Industry Co., Ltd.'),
      ('VNHUNHA99HUN', 'Hung Ha Garment Production and Import-Export Co., Ltd.'),
      ('VNVANPHA99HOC', 'AN VAN PHAT GROUP Co., Ltd.'),
      ('VNKHUMAI3661HOC', 'Khuong Mai Co., Ltd.'),
      ('KHFOMCAMPHN', 'Foms (Cambodia) Garment Co., Ltd.'),
      ('VNGLOFAS52HOC', 'Global Fashion'),
      ('KHJIN1019PHN', 'Jinxiu'),
      ('KHSHUYIN30PHN', 'Shun Ying Jiu Garment Co., Ltd.'),
      ('VNNAMPHA1HAN', 'Nam Phat Import - Export Production Trade JSC'),
      ('KHAOKGARPHN', 'Aokai Garments Co., Ltd.'),
      ('VNTHAPHA9932HOC', 'Thanh Phat Garment Production and Import-Export Company Limited'),
      ('KHCHESHI122PHN', 'CHENG SHI XIN MANUFACTURINGCOMPANY LIMITED'),
      ('VNBELTEX1678HOC', 'Bella Textile Company Limited'),
      ('KHMOOTAIPHN', 'Great New Talent Factory (Cambodia) Co,LTD'),
      ('VNGARPRO9913BIN', 'X Garment Production & Trading Co., Ltd.'),
      ('KHCAMFOR1PHN', 'Cam Forever Co., Ltd Garment Factory'),
      ('VNANHPHA996BAC', 'The Anh Phat Garment Co., Ltd.'),
      ('VNLONQIY202LON', 'CONG TYTNHH MAY MAC LONGAN QIYUE'),
      ('VNDONVIE21HOC', 'DONY VIETNAM COMPANY LIMITED'),
      ('KHHUASHA188KAN', 'Huanan Shanggu Apparel (Cambodia) Co., Ltd.'),
      ('VNBYUS36HOC', 'BY US Joint Stock Company'),
      ('KHOPTGARPHN', 'Optima Garment (Cambodia) Co., Ltd.'),
      ('VNTUYTHA361HAI', 'NEW FACE SERVICE TRADING INVESTMENT LIMITED COMPANY'),
      ('VNTRUTHA171HOC', 'Truong Thao Garment Joint Stock Company'),
      ('KHCAMXIN2PHN', 'CAMBODIAN XIN HUANG MING GARMENT CO.,LTD.'),
      ('VNAPDGARBEN', 'APD Garment Manufacturing Limited Company'),
      ('VNSDGLO3HUN', 'SD Global Vina Garment Export Co., Ltd.'),
      ('KHRUISEN15PHN', 'Linglingxiu Clothing Limited'),
      ('VNINDINTHUN', 'Indico International Trading and Garment Joint Stock Company'),
      ('VNDANMIN515DON', 'Dang Minh Phat Fashion Co., Ltd.'),
      ('VNTHILOC2739BIN', 'Thien Loc Vietnam Import Export Co., Ltd.'),
      ('VNGGLON2HOC', 'G&G LONG AN FASHION CO., LTD'),
      ('VNHAIDUO43HAN', 'Hai Duong Dai Duong Company Limited'),
      ('KHYUETUN85PHN', 'Yuen Tung Clothing Co., Ltd.'),
      ('VNHANTIE9923HAI', 'Han Tien Garment Import Export and Production One Member Company Limited'),
      ('KHFENGAR1PHN', 'Fengsheng Garment Factory'),
      ('KHCAMVIT2PHN', 'CAMBO VITALITY GARMENT CO., LTD.'),
      ('KHDEXIAPHN', 'De Xiang Garment Co., Ltd.'),
      ('KHCENCAM2PHN', 'Centric (Cambodia) Garment Co., Ltd.'),
      ('VNKIMLONHUN', 'Kim Long Garment Co., Ltd.'),
      ('VNDONCLO126THA', 'DONGMAO CLOTHING TRADE LIMITED'),
      ('VNYLDGARHUN', 'YLD Garment Co., Ltd.'),
      ('KHXINHONPHN', 'Xin Hong Peng (Cambodia) Knitting Co., Ltd.'),
      ('VNCATTUO121HOC', 'Cat Tuong Garment Export Co., Ltd.'),
      ('VNSAIGON464HOC', 'Sai Gon Garments Company Limited'),
      ('VNDARFASHAI', 'Darwin Fashion Production and Supply Co., Ltd.'),
      ('KHETEFAMPHN', 'Eternal Fame (Cambodia) Garments Co., Ltd.'),
      ('VNTHATRA297HAN', 'Thai Trang Hang Phong Production Trading Co., Ltd.'),
      ('VNTHIPHU19HOC', 'Thien Phu Fashion Company Limited'),
      ('VNCHUYU344BIN', 'Chuang Yu International Trading Co., Ltd.'),
      ('VNKIMLOI41HOC', 'Kim Loi Lai Garment Co.,Ltd'),
      ('VNTPPGAR245HOC', 'TPP Garment One Member Co., Ltd.'),
      ('KHSUNGAR2PHN', 'Sunrise Garment Co., Ltd.'),
      ('KHSANTAIPHN', 'SANTA TAI FACTORY CO., LTD'),
      ('VNDARFASHAN', 'Darwin Fashion Production and Supply Company Limited'),
      ('VNMINDATTHA', 'MINH DAT – THANH HOA COOPERATIVE'),
      ('VNREGMIR9HAI', 'Regina Miracle International (Vietnam) Co., Ltd.'),
      ('KHRUISEN1PHN', 'RUI SEN JIA GARMENT CO.,LTD.'),
      ('VNPHOVIENIN', 'Phoenix Vietnam Investment and Production Joint Stock Company'),
      ('VNWINVIE4HAI', 'Wingsburg Vietnam Co., Ltd.'),
      ('VNMINVIE9928HAI', 'Minh Viet Phat Trading and Manufacturing Company Limited'),
      ('VNVANPHA98HOC', 'AN VAN PHAT GROUP COMPANY LIMITED'),
      ('VNTHABIN9902THA', 'Thai Binh Tue Com Co., Ltd.'),
      ('VNBACTHI62BIN', 'Bach Thinh'),
      ('VNLEEFAS99HOC', 'LEE FASHION TRADING AND PRODUCTION COMPANY LIMITED'),
      ('KHBUSGAR130PHN', 'PROGRESSIVE GARMENT CO.,LTD'),
      ('KHYOU44KAM', 'YOUNG2'),
      ('VNVIEHANHUN', 'VIET HAN SJC GARMENT COMPANY LIMITED'),
      ('VNHANHONHAN', 'Hanjie Garment Co., Ltd.'),
      ('KHHSXLTD1928PHN', 'H.S.XPRINTINGEMBROIDERYCO.,LTD.'),
      ('VNHNTGAR2HOC', 'HNT Garment Import Export Limited Company'),
      ('KHSANTAITAK', 'SANTA TAI FACTORY CO., LTD.')
)
INSERT INTO midmap.canonical_manufacturers(good_mid, manufacturer_name)
SELECT btrim(upper(good_mid)), NULLIF(btrim(manufacturer_name), '')
FROM canon
WHERE good_mid IS NOT NULL
ON CONFLICT (good_mid) DO UPDATE
  SET manufacturer_name = COALESCE(midmap.canonical_manufacturers.manufacturer_name,
                                   EXCLUDED.manufacturer_name);

-- 2) Name mappings: manufacturer_name -> good_mid
WITH stg(manufacturer_name, good_mid, created_by) AS (
  VALUES
      ('Jinhua Jindong District Liju Ecommerce Firm', 'CNJINJIN5547JIN', 'ZOEY @ JFK'),
      ('GanZhouPanHongTechnology', 'CNGAN806GAN', 'ZOEY @ JFK'),
      ('LINZHOUJINPENGSHANGMAO CO..LTD.', 'CNLINCOL1126ANY', 'ZOEY @ JFK'),
      ('NO.1177,BINHAI, LONGWAN, WENZHOU.', 'CNNO1BIN303JIN', 'ZOEY @ JFK'),
      ('XINYUSHIXIANNVHUQUQIANHEBAIHUIZHIXIECHANG', 'CNXIN9104XIN', 'ZOEY @ JFK'),
      ('Wenzhoushifengyiwujinzhipin Co., Ltd.', 'CNWENCO26WEN', 'ZOEY @ JFK'),
      ('XINGCHENGHUIMEICLOTHINGMANUFACTURINGFACTORY', 'CNXIN2100HUL', 'ZOEY @ JFK'),
      ('FOSHANSHIMMUPINGFUSHI O..LTD.', 'CNFOSOLT1090FOS', 'ZOEY @ JFK'),
      ('Haomiao.electronic.commerce co.,ltd', 'CNHAOCOL912TAI', 'ZOEY @ JFK'),
      ('ZHONGQINMAOYIGUANGZHOU CO..LTD', 'CNZHOCOL493GUA', 'ZOEY @ JFK'),
      ('GUANGZHOUSHILINGLINGQIKEJIFAZHANCO.LTD.', 'CNGUA2330GUA', 'ZOEY @ JFK'),
      ('NO.5, PETROLEUM ROAD', 'CNNO5PET5XIA', 'ZOEY @ JFK'),
      ('PUJIANG MEMORY TOY CO., LTD', 'CNPUJMEM8282JIN', 'Cheng @ JFK'),
      ('JINHUASHIQINRONGMAOYI CO.LTD', 'CNJINCOL360JIN', 'Cheng @ JFK'),
      ('ANHUI HEYE NETWORK TECHNOLOGY CO., LTD', 'CNANHHEY2105HEF', 'Cheng @ JFK'),
      ('SHENZHENJIAMIWANGLUOISHUCO..LTD', 'CNSHE179SHE', 'Cheng @ JFK'),
      ('SHENZHENSHIANRUNTAIKEJICO.LTD.', 'CNSHE1353SHE', 'Cheng @ JFK'),
      ('GUANGZHOU AICHUANGJINCHUKOUMAOYI CO., LTD.', 'CNGUAAIC3183GUA', 'Cheng @ JFK'),
      ('Fujian Chengrui Shoes Industry Co. , Ltd.', 'CNFUJCHE814FUZ', 'Cheng @ JFK'),
      ('PANAN JINGYA HORTICULTURAL SUPPLIES FACTORY', 'CNPANJIN202JIN', 'Cheng @ JFK'),
      ('HUAIYUANXINHAODIANZISHANGWU CO.LTD.', 'CNHUACOL104BEN', 'Cheng @ JFK'),
      ('GUANGZHOUTONGRUNTRADINGCO..LTD', 'CNGUA162JIE', 'Cheng @ JFK'),
      ('HUIYU WOMEN''S SHOE FACTORY', 'CNHUIWOM2282XIN', 'Cheng @ JFK'),
      ('Foshan Shanmu clothing Co., LTD', 'CNFOSSHA2450FOS', 'Cheng @ JFK'),
      ('HUIZHOU DUDU PET PRODUCTS CO., ITD', 'CNHUIDUD234HUI', 'Cheng @ JFK'),
      ('Hengyang City Coarse Tea and Rice Catering Culture Ltd', 'CNHENCIT153HEN', 'Cheng @ JFK'),
      ('JINHUAGUOYOUHOMEFURNISHINGCO.LTD', 'CNJIN890JIN', 'Cheng @ JFK'),
      ('TAIZHOUSHIDAHONGBAOGONGYIPIN CO.LTD.', 'CNTAICOL413TAI', 'Cheng @ JFK'),
      ('Foshanshixuntuodianzico.Ltd', 'CNFOS2119FOS', 'Cheng @ JFK'),
      ('YIWUSHIYOUKEJINCHUKOUCO.LTD.', 'CNYIW2310JIN', 'Cheng @ JFK'),
      ('GUANGZHAUYUNNIFUSHICO.LTD.', 'CNGUA1076GUA', 'Cheng @ JFK'),
      ('ZHEJIANG MENGDA IMPORT AND EXPORT CO., LTD.', 'CNZHEMEN1188JIN', 'Cheng @ JFK'),
      ('SHENZHENSHIDONGHEXINKEJI.CO,.LTD', 'CNSHELTD238SHE', 'Cheng @ JFK'),
      ('MOUDING COUNTY KUNI DEPARTMENT STORE SOLE PROPRIETORSHIP', 'CNMOUCOU2744CHU', 'Cheng @ JFK'),
      ('SHANDONGTAHAIWANGLUOKEJI CO.LTD.', 'CNSHACOL1595RIZ', 'ZOEY @ JFK'),
      ('GUANGZHOUHUIWANGDIANZISHANGWUCO..LTD', 'CNGUA850DON', 'ZOEY @ JFK'),
      ('Xingcheng Kaisheng Garment Co., Ltd.', 'CNKAIGARXIN', 'Cheng @ JFK'),
      ('Xingcheng Kaiwei Garment Co., Ltd.', 'CNXINKAI6543HUL', 'Cheng @ JFK'),
      ('Xingcheng Kairuida Garment Co', 'CNKAIGARHUL', 'Cheng @ JFK'),
      ('Dongguan Shanjia Clothing Co., Ltd.', 'CNDONSHA800DON', 'JC @ JFK'),
      ('DONGMING CO.LTD', 'CNDONCOL364FUZ', 'JC @ JFK'),
      ('Baoding Chenchuang Trading Co., Ltd.', 'CNCHECHUBAO', 'Cheng @ JFK'),
      ('Taizhou Borui Industry and Trade Co., Ltd.', 'CNTAIINDTAI', 'JC @ JFK'),
      ('Zhuji Jiuzhi Textile Factory', 'CNZHUJIU99SHA', 'JC @ JFK'),
      ('Baigou New Town Yaohuo Bags Factory (individual business owner)', 'CNBAINEW297BAO', 'JC @ JFK'),
      ('Xinyu Zulu Shoes Co., Ltd.', 'CNXINZUL1819XIN', 'JC @ JFK'),
      ('Suzhou Tianbianyou Culture Media Co., Ltd.', 'CNSUZTIA4555SUZ', 'JC @ JFK'),
      ('Huangshi Chaoju Clothing Store, Baiyun District, Guangzhou City', 'CNHUACHA570GUA', 'ZOEY @ JFK'),
      ('Nan''an Meishan Hesheng Knitting Factory', 'CNMEIHESQUA', 'JW @ JFK'),
      ('Shantou Buyun Clothing Co., Ltd.', 'CNBUYCLOSHA', 'JW @ JFK'),
      ('Dongguan Dingyangfeng Fashion Co., Ltd.', 'CNDINFAS501DON', 'JW @ JFK'),
      ('Xingcheng Kairuida Garment Co., Ltd.', 'CNXINKAI1HUL', 'JW @ JFK'),
      ('Yueqing Mengfu International Trade Co., Ltd.', 'CNYUEMEN46WEN', 'JW @ JFK'),
      ('Yiwu Yaqin Electronic Commerce Company (individual business owner)', 'CNYIWYAQ205JIN', 'JW @ JFK'),
      ('Yiwu Yaoer Ecommerce Co., Ltd.', 'CNYIWU146JIN', 'JW @ JFK'),
      ('Shenzhen 85 WinWin Trading Co., Ltd.', 'CNSHE85SHA', 'JW @ JFK'),
      ('Shenzhen Dechuang Photoelectric Technology Co., Ltd', 'CNSHEZHE6SHE', 'JW @ JFK'),
      ('Guangzhou Zuomu Trading Co., Ltd.', 'CNGUAZUO108GUA', 'JW @ JFK'),
      ('Guangzhou Huiya Garment Co., Ltd.', 'CNGUAHUI302GUA', 'JW @ JFK'),
      ('Yiwu Qiangkuang Ecommerce Store (Individual Business)', 'CNQIAECO2JIN', 'JW @ JFK'),
      ('Changge City Zhubao General Store (Individual Business)', 'CNZHUBAO164XUC', 'JW @ JFK'),
      ('GUANGZHOUPEISHANFUZHUANGGONGYINGLIANGUANICO.LTD', 'CNPEISHA2263GUA', 'Cheng @ JFK'),
      ('Wenzhoushensengongju Co., Ltd.', 'CNSHESENWEN', 'Cheng @ JFK'),
      ('GanZhouPanHong Technology Co., LTD', 'CNGANTEC1026GAN', 'Cheng @ JFK'),
      ('Wenzhouyihewanjuzhizao Co., Ltd.', 'CNWENCO497WEN', 'Cheng @ JFK'),
      ('Jinhua Jindong District Liju E-commerce Firm', 'CNJINJIN5547JIN', 'Cheng @ JFK'),
      ('GUANGXIPINGNANXIANYUHANKEJI CO..LTD', 'CNGUACOL2202GUI', 'Cheng @ JFK'),
      ('SHENZHEN BEAUTIFUL STORY TRADING CO., LTD.', 'CNSHEBEA3241SHE', 'Cheng @ JFK'),
      ('BANANA TOOTH CLOTHING CO.LTD', 'CNBANTOO463GUA', 'Cheng @ JFK'),
      ('SHENZHENJIECHANGSHENGINDUSTRIALCO..LTD', 'CNSHE683SHE', 'Cheng @ JFK'),
      ('SHENZHENTUOWEIDIANZISHANGWUCO.LTD.', 'CNSHE201SHE', 'Cheng @ JFK'),
      ('Wenzhouheshengsujiao Co., Ltd.', 'CNHESSUJWEN', 'Cheng @ JFK'),
      ('Wenzhouchangchuangshangmao Co., Ltd.', 'CNWENZHOWEN', 'Cheng @ JFK'),
      ('FOSHANBEISHIYUFUSHI CO., LTD.', 'CNFOSOLT1090FOS', 'Cheng @ JFK'),
      ('SHANDONGSIBANGGONGJU CO.LTD', 'CNXINKAI6543HUL', 'Cheng @ JFK'),
      ('WENZHOUFEIMUCLOTHINGCO.LTD', 'CNWENZHOWEN', 'Cheng @ JFK'),
      ('ZHENGZHOUAMIERMAOYI CO.LTD', 'CNSHEPHO6SHE', 'Cheng @ JFK'),
      ('PUJIANGXIANFULIUMANMAOYICO.LTD.', 'CNLANSEA2236HUL', 'Cheng @ JFK'),
      ('Wenzhoushimikaixieye Co., Ltd.', 'CNWENZHOWEN', 'Cheng @ JFK'),
      ('rizhaozhulongfangzhiyouxiangongsi', 'CNSHEPHO6SHE', 'Cheng @ JFK'),
      ('YIWU XINMAN JEWELRY CO. LTD', 'CNBAOCHE6BAO', 'Cheng @ JFK'),
      ('Wan Ly (Cambodia) Garment Co., Ltd.', 'KHWANLY137PHN', 'Cheng @ JFK'),
      ('Lonso (Cambodia) Garment Co., Ltd.', 'KHLONCAMPHN', 'Cheng @ JFK'),
      ('Xundu International Trading Company Limited', 'KHXUNINT32PHN', 'Cheng @ JFK'),
      ('THAM VAN COMPANY LIMITED', 'VNTHAVANHAI', 'Cheng @ JFK'),
      ('New Jing Feng (Cambodia) Garment Co., Ltd.', 'KHNEWJINPHN', 'Cheng @ JFK'),
      ('Vietnam Shangya Company Limited', 'VNVIESHA2180BIN', 'Cheng @ JFK'),
      ('MB Vietnam Garment Production Trading Service Co., Ltd.', 'VNMBVIE5817HOC', 'Cheng @ JFK'),
      ('Gia Phuc Development Production Trading Service Co., Ltd.', 'VNGIAPHU30HOC', 'Cheng @ JFK'),
      ('San Mateo Garment (Cambodia) Co., Ltd.', 'KHSANMATPHN', 'Cheng @ JFK'),
      ('Dai Duong Hai Duong Company Limited', 'VNDAIDUO43HAN', 'Cheng @ JFK'),
      ('YINIFU CLOTHING COMPANY LIMITED', 'VNYINGAR52BIN', 'Cheng @ JFK'),
      ('Chan Hung Garment Import-Export Production Co., Ltd.', 'VNCHAHUN30HOC', 'Cheng @ JFK'),
      ('YENI GOLDEN IMPORT EXPORT TRADING COMPANY LIMITED', 'VNYENGOL814HOC', 'Cheng @ JFK'),
      ('Joy Vina Fashion Co., Ltd.', 'VNJOYVINHUN', 'Cheng @ JFK'),
      ('Yi Lan Ji Garment (Cambodia) Co., Ltd.', 'KHYILAN18PHN', 'Cheng @ JFK'),
      ('CHAN HUNG IMPORT EXPORT GARMENT PRODUCTION COMPANY LIMITED', 'VNCHAHUN1826HOC', 'Cheng @ JFK'),
      ('XIYIN VIETNAM DISTRIBUTION COMPANY LIMITED', 'KHXIYVIE1206PHN', 'Cheng @ JFK'),
      ('Saigon Garments Co., Ltd.', 'VNSAIGAR464HOC', 'Cheng @ JFK'),
      ('Cam Forever Co., Ltd.', 'KHCAMFORPHN', 'Cheng @ JFK'),
      ('Duy Minh Phat Trading Production Garment Import Export Co., Ltd.', 'VNDUYMIN28HOC', 'Cheng @ JFK'),
      ('Rui Wen Aries (Cambodia) Garments Co., Ltd.', 'KHRUIWEN27PHN', 'Cheng @ JFK'),
      ('KHOI NGHIEP GARMENT COMPANY LIMITED', 'VNCHUGAR1THA', 'Cheng @ JFK'),
      ('Joy Rich Garment (Cambodia) Co., Ltd.', 'KHJOYRIC6KAM', 'Cheng @ JFK'),
      ('Tan Hai Sinh', 'VNTANHAI3904HOC', 'Cheng @ JFK'),
      ('Dai Ma Garment Import-Export Company Limited', 'VNDAIMA24THA', 'Cheng @ JFK'),
      ('New Era (Cambodia) Cashmere Textile Co., Ltd.', 'KHNEWERA21PHN', 'Cheng @ JFK'),
      ('Si Xin Underwear Factory', 'KHSIXINKAN', 'Cheng @ JFK'),
      ('Shangya Vietnam Co., Ltd.', 'VNSHAVIE2180BIN', 'Cheng @ JFK'),
      ('Thien Hung Phat Factory', 'VNTHIHUN225HOC', 'Cheng @ JFK'),
      ('Thinh Phong Fashion Company Limited', 'VNTHIPHO475HOC', 'Cheng @ JFK'),
      ('Hongruida Garment (Cambodia) Co., Ltd.', 'KHHONGAR34KAN', 'Cheng @ JFK'),
      ('Truong Phat Hanoi Production and Trading Company Limited', 'VNTRUPHAHAN', 'Cheng @ JFK'),
      ('CAO LONG PRODUCTION AND TRADING COMPANY LIMITED', 'VNCAOLON3HOC', 'Cheng @ JFK'),
      ('BLUE VISTA CO.,LTD.', 'KHBLUVIS789PHN', 'Cheng @ JFK'),
      ('Chicbuck (Cambodia) Garments Manufacturing Co., Ltd.', 'KHCHICAMPHN', 'Cheng @ JFK'),
      ('Active Seamless (Cambodia) Co.,LTD', 'KHACTSEA130PHN', 'Cheng @ JFK'),
      ('Grandfield Industry Co., Ltd.', 'KHGRAINDPHN', 'Cheng @ JFK'),
      ('Hung Ha Garment Production and Import-Export Co., Ltd.', 'VNHUNHA99HUN', 'Cheng @ JFK'),
      ('AN VAN PHAT GROUP Co., Ltd.', 'VNVANPHA99HOC', 'Cheng @ JFK'),
      ('Khuong Mai Co., Ltd.', 'VNKHUMAI3661HOC', 'Cheng @ JFK'),
      ('Foms (Cambodia) Garment Co., Ltd.', 'KHFOMCAMPHN', 'Cheng @ JFK'),
      ('Blue Vista Co., Ltd.', 'KHBLUVIS789PHN', 'Cheng @ JFK'),
      ('Global Fashion', 'VNGLOFAS52HOC', 'Cheng @ JFK'),
      ('Jinxiu', 'KHJIN1019PHN', 'Cheng @ JFK'),
      ('Shun Ying Jiu Garment Co., Ltd.', 'KHSHUYIN30PHN', 'Cheng @ JFK'),
      ('Nam Phat Import - Export Production Trade JSC', 'VNNAMPHA1HAN', 'Cheng @ JFK'),
      ('Aokai Garments Co., Ltd.', 'KHAOKGARPHN', 'Cheng @ JFK'),
      ('Thanh Phat Garment Production and Import-Export Company Limited', 'VNTHAPHA9932HOC', 'Cheng @ JFK'),
      ('CHENG SHI XIN MANUFACTURINGCOMPANY LIMITED', 'KHCHESHI122PHN', 'Cheng @ JFK'),
      ('Bella Textile Company Limited', 'VNBELTEX1678HOC', 'Cheng @ JFK'),
      ('Great New Talent Factory (Cambodia) Co,LTD', 'KHMOOTAIPHN', 'Cheng @ JFK'),
      ('X Garment Production & Trading Co., Ltd.', 'VNGARPRO9913BIN', 'Cheng @ JFK'),
      ('Cam Forever Co., Ltd Garment Factory', 'KHCAMFOR1PHN', 'Cheng @ JFK'),
      ('The Anh Phat Garment Co., Ltd.', 'VNANHPHA996BAC', 'Cheng @ JFK'),
      ('CONG TYTNHH MAY MAC LONGAN QIYUE', 'VNLONQIY202LON', 'Cheng @ JFK'),
      ('DONY VIETNAM COMPANY LIMITED', 'VNDONVIE21HOC', 'Cheng @ JFK'),
      ('Yeni Golden Import Export Trading Co., Ltd.', 'VNYENGOL814HOC', 'Cheng @ JFK'),
      ('Huanan Shanggu Apparel (Cambodia) Co., Ltd.', 'KHHUASHA188KAN', 'Cheng @ JFK'),
      ('BY US Joint Stock Company', 'VNBYUS36HOC', 'Cheng @ JFK'),
      ('Optima Garment (Cambodia) Co., Ltd.', 'KHOPTGARPHN', 'Cheng @ JFK'),
      ('NEW FACE SERVICE TRADING INVESTMENT LIMITED COMPANY', 'VNTUYTHA361HAI', 'Cheng @ JFK'),
      ('Truong Thao Garment Joint Stock Company', 'VNTRUTHA171HOC', 'Cheng @ JFK'),
      ('CAMBODIAN XIN HUANG MING GARMENT CO.,LTD.', 'KHCAMXIN2PHN', 'Cheng @ JFK'),
      ('APD Garment Manufacturing Limited Company', 'VNAPDGARBEN', 'Cheng @ JFK'),
      ('SD Global Vina Garment Export Co., Ltd.', 'VNSDGLO3HUN', 'Cheng @ JFK'),
      ('Linglingxiu Clothing Limited', 'KHRUISEN15PHN', 'Cheng @ JFK'),
      ('Indico International Trading and Garment Joint Stock Company', 'VNINDINTHUN', 'Cheng @ JFK'),
      ('Dang Minh Phat Fashion Co., Ltd.', 'VNDANMIN515DON', 'Cheng @ JFK'),
      ('Thien Loc Vietnam Import Export Co., Ltd.', 'VNTHILOC2739BIN', 'Cheng @ JFK'),
      ('Thanh Phat Garment Import-Export Production Co., Ltd.', 'VNTHAPHA9932HOC', 'Cheng @ JFK'),
      ('G&G LONG AN FASHION CO., LTD', 'VNGGLON2HOC', 'Cheng @ JFK'),
      ('Hai Duong Dai Duong Company Limited', 'VNHAIDUO43HAN', 'Cheng @ JFK'),
      ('Yuen Tung Clothing Co., Ltd.', 'KHYUETUN85PHN', 'Cheng @ JFK'),
      ('Han Tien Garment Import Export and Production One Member Company Limited', 'VNHANTIE9923HAI', 'Cheng @ JFK'),
      ('Fengsheng Garment Factory', 'KHFENGAR1PHN', 'Cheng @ JFK'),
      ('CAMBO VITALITY GARMENT CO., LTD.', 'KHCAMVIT2PHN', 'Cheng @ JFK'),
      ('De Xiang Garment Co., Ltd.', 'KHDEXIAPHN', 'Cheng @ JFK'),
      ('ASIA PACIFIC DREAMAX GARMENT(CAMBODIA)CO.,LTD.', 'KHYILAN18PHN', 'Cheng @ JFK'),
      ('Centric (Cambodia) Garment Co., Ltd.', 'KHCENCAM2PHN', 'Cheng @ JFK'),
      ('Kim Long Garment Co., Ltd.', 'VNKIMLONHUN', 'Cheng @ JFK'),
      ('DONGMAO CLOTHING TRADE LIMITED', 'VNDONCLO126THA', 'Cheng @ JFK'),
      ('YLD Garment Co., Ltd.', 'VNYLDGARHUN', 'Cheng @ JFK'),
      ('Xin Hong Peng (Cambodia) Knitting Co., Ltd.', 'KHXINHONPHN', 'Cheng @ JFK'),
      ('Cat Tuong Garment Export Co., Ltd.', 'VNCATTUO121HOC', 'Cheng @ JFK'),
      ('Sai Gon Garments Company Limited', 'VNSAIGON464HOC', 'Cheng @ JFK'),
      ('Darwin Fashion Production and Supply Co., Ltd.', 'VNDARFASHAI', 'Cheng @ JFK'),
      ('Eternal Fame (Cambodia) Garments Co., Ltd.', 'KHETEFAMPHN', 'Cheng @ JFK'),
      ('Thai Trang Hang Phong Production Trading Co., Ltd.', 'VNTHATRA297HAN', 'Cheng @ JFK'),
      ('Thien Phu Fashion Company Limited', 'VNTHIPHU19HOC', 'Cheng @ JFK'),
      ('Chuang Yu International Trading Co., Ltd.', 'VNCHUYU344BIN', 'Cheng @ JFK'),
      ('Kim Loi Lai Garment Co.,Ltd', 'VNKIMLOI41HOC', 'Cheng @ JFK'),
      ('TPP Garment One Member Co., Ltd.', 'VNTPPGAR245HOC', 'Cheng @ JFK'),
      ('Sunrise Garment Co., Ltd.', 'KHSUNGAR2PHN', 'Cheng @ JFK'),
      ('SANTA TAI FACTORY CO., LTD', 'KHSANTAIPHN', 'Cheng @ JFK'),
      ('Darwin Fashion Production and Supply Company Limited', 'VNDARFASHAN', 'Cheng @ JFK'),
      ('TPP Garment One Member Limited Liability Company', 'VNTPPGAR245HOC', 'Cheng @ JFK'),
      ('MINH DAT – THANH HOA COOPERATIVE', 'VNMINDATTHA', 'Cheng @ JFK'),
      ('Regina Miracle International (Vietnam) Co., Ltd.', 'VNREGMIR9HAI', 'Cheng @ JFK'),
      ('Han Tien Garment Import, Export and Production One Member Limited Liability Company', 'VNHANTIE9923HAI', 'Cheng @ JFK'),
      ('RUI SEN JIA GARMENT CO.,LTD.', 'KHRUISEN1PHN', 'Cheng @ JFK'),
      ('Phoenix Vietnam Investment and Production Joint Stock Company', 'VNPHOVIENIN', 'Cheng @ JFK'),
      ('Wingsburg Vietnam Co., Ltd.', 'VNWINVIE4HAI', 'Cheng @ JFK'),
      ('Minh Viet Phat Trading and Manufacturing Company Limited', 'VNMINVIE9928HAI', 'Cheng @ JFK'),
      ('DANG MINH PHAT FASHION COMPANY', 'VNDANMIN515DON', 'Cheng @ JFK'),
      ('AN VAN PHAT GROUP COMPANY LIMITED', 'VNVANPHA98HOC', 'Cheng @ JFK'),
      ('Thai Binh Tue Com Co., Ltd.', 'VNTHABIN9902THA', 'Cheng @ JFK'),
      ('Bach Thinh', 'VNBACTHI62BIN', 'Cheng @ JFK'),
      ('DANG MINH PHAT FASHION COMPANY LIMITED', 'VNDANMIN515DON', 'Cheng @ JFK'),
      ('LEE FASHION TRADING AND PRODUCTION COMPANY LIMITED', 'VNLEEFAS99HOC', 'Cheng @ JFK'),
      ('PROGRESSIVE GARMENT CO.,LTD', 'KHBUSGAR130PHN', 'Cheng @ JFK'),
      ('YOUNG2', 'KHYOU44KAM', 'Cheng @ JFK'),
      ('VIET HAN SJC GARMENT COMPANY LIMITED', 'VNVIEHANHUN', 'Cheng @ JFK'),
      ('AN BINH BG GARMENT COMPANY LIMITED', 'VNBINBGBAC', 'Cheng @ JFK'),
      ('HUNG FUNG GARMENT (VIETNAM) CO., LTD', 'VNHUNFUN24DAK', 'Cheng @ JFK'),
      ('Hanjie Garment Co., Ltd.', 'VNHANHONHAN', 'Cheng @ JFK'),
      ('SAN XUAT AND THUONG MAI TRUONG PHAT HA NOI COMPANY LIMITED.', 'VNTRUPHAHAN', 'Cheng @ JFK'),
      ('Chuangye Garment Co., Ltd.', 'VNCHUGAR1THA', 'Cheng @ JFK'),
      ('Rui Sen Factory', 'KHRUISEN15PHN', 'Cheng @ JFK'),
      ('Active Seamless (Cambodia) Garment Co., Ltd.', 'KHACTSEA130PHN', 'Cheng @ JFK'),
      ('Long An Qiyue Garment Co., Ltd.', 'VNLONQIY202LON', 'Cheng @ JFK'),
      ('G&G Long An Fashion Production Trading One Member Co., Ltd.', 'VNGGLON2HOC', 'Cheng @ JFK'),
      ('Kim Loi Lai Garment Co., Ltd.', 'VNKIMLOI41HOC', 'Cheng @ JFK'),
      ('H.S.XPRINTINGEMBROIDERYCO.,LTD.', 'KHHSXLTD1928PHN', 'Cheng @ JFK'),
      ('Busheng Garment Co., Ltd.', 'KHBUSGAR130PHN', 'Cheng @ JFK'),
      ('HNT Garment Import Export Limited Company', 'VNHNTGAR2HOC', 'Cheng @ JFK'),
      ('CHENG SHI XIN MANUFACTURING（CAMBODIA）COMPANY LIMITED', 'KHCHESHI122PHN', 'Cheng @ JFK'),
      ('CAMBO VITALITY GARMENT CO.. LTD', 'KHCAMVIT2PHN', 'Cheng @ JFK'),
      ('SANTA TAI FACTORY CO., LTD.', 'KHSANTAITAK', 'Cheng @ JFK')
)
INSERT INTO midmap.name_mappings(manufacturer_name, good_manufacturer_id, created_by)
SELECT NULLIF(btrim(s.manufacturer_name), ''),
       cm.id,
       NULLIF(btrim(s.created_by), '')
FROM stg s
JOIN midmap.canonical_manufacturers cm ON cm.good_mid = btrim(upper(s.good_mid))
WHERE NULLIF(btrim(s.manufacturer_name), '') IS NOT NULL
ON CONFLICT (manufacturer_name) DO UPDATE
  SET good_manufacturer_id = EXCLUDED.good_manufacturer_id;

-- 3) Aliases: bad_mid -> good_mid
WITH stg(bad_mid, good_mid, created_by) AS (
  VALUES
      ('CNDONDIN501DON', 'CNDONSHA800DON', 'JC @ JFK'),
      ('CNSUZTIA455SUZ', 'CNSUZTIA4555SUZ', 'JC @ JFK'),
      ('CNBAINEW002BAO', 'CNBAINEW857BAO', 'Alex @ JFK'),
      ('CNGAOXIN0225BAO', 'CNGAOXIN9902BAO', 'Alex @ JFK'),
      ('CNFOSFEI03FOS', 'CNFOSFEI302FOS', 'Alex @ JFK'),
      ('CNBAINEW06BAO', 'CNBAINEW9906BAO', 'Alex @ JFK'),
      ('CNGAONEW0426BAO', 'CNGAONEW9904BAO', 'Alex @ JFK'),
      ('CNBAOBOP0132BAO', 'CNBAOBOP132BAO', 'Alex @ JFK'),
      ('CNFOSANY03FOS', 'CNFOSANY9903FOS', 'Alex @ JFK'),
      ('CNHANYIF5715HAN', 'CNHANYIF603HAN', 'Alex @ JFK'),
      ('CNHUBSHU213TIA', 'CNHUBSHU21TIA', 'Alex @ JFK'),
      ('CNXINZUL35XIN', 'CNXINZUL1819XIN', 'Alex @ JFK'),
      ('CNHONBEI13FOS', 'CNHONBEI3FOS', 'Alex @ JFK'),
      ('CNDONMAO938JIN', 'CNDONMAO93JIN', 'Alex @ JFK'),
      ('CNDAQZHA1DAQ', 'CNDAQZHA3DAQ', 'Alex @ JFK'),
      ('CNGUAYUX066GUA', 'CNGUAYUX9906GUA', 'Alex @ JFK'),
      ('CNBAOSHU1BAO', 'CNBAOSHU5BAO', 'Alex @ JFK'),
      ('CNGAOXIN0421BAO', 'CNGAOXIN421BAO', 'Alex @ JFK'),
      ('CNGAOXIN0307BAO', 'CNGAOXIN3071BAO', 'Alex @ JFK'),
      ('CNHAIMEI03HAI', 'CNHAIMEI118HAI', 'Alex @ JFK'),
      ('CNHEJIA18JIN', 'CNHEJIA19JIN', 'Alex @ JFK'),
      ('CNGAOXIN0623BAO', 'CNGAOXIN623BAO', 'Alex @ JFK'),
      ('CNBEIHEN3YUL', 'CNBEIHEN4YUL', 'Alex @ JFK'),
      ('CNGUAHEL335GUA', 'CNGUAHEL521GUA', 'Alex @ JFK'),
      ('CNYIWKUN1JIN', 'CNYIWKUN704JIN', 'Alex @ JFK'),
      ('CNFOSKAQ10FOS', 'CNFOSKAQ48FOS', 'Alex @ JFK'),
      ('CNZHEOST10ZHE', 'CNZHEOST403ZHE', 'Alex @ JFK'),
      ('CNGUAFUH4GUA', 'CNGUAFUH9GUA', 'Alex @ JFK'),
      ('CNYUECOU04ANQ', 'CNYUECOU4ANQ', 'Alex @ JFK'),
      ('CNSHEQIN01SHE', 'CNSHEQIN984SHE', 'Alex @ JFK'),
      ('CNBAOCHEBAO', 'CNBAOCHE99BAO', 'Alex @ JFK'),
      ('CNXIASUP021ZHU', 'CNXIASUP89ZHU', 'Alex @ JFK'),
      ('CNYUAHOM068SUI', 'CNYUAHOM68SUI', 'Alex @ JFK'),
      ('CNYIWQIS1104JIN', 'CNYIWQIS1666JIN', 'Alex @ JFK'),
      ('CNZHEAIY002JIN', 'CNZHEAIY9900JIN', 'Alex @ JFK'),
      ('CNXINZUL18XIN', 'CNXINZUL1819XIN', 'Alex @ JFK'),
      ('CNYUEREM4ANQ', 'CNYUEREM9ANQ', 'Alex @ JFK'),
      ('CNKUADEP0098FOS', 'CNKUADEP511FOS', 'Alex @ JFK'),
      ('CNBAINEW024BAO', 'CNBAINEW787BAO', 'Alex @ JFK'),
      ('CNGAOXIN0419BAO', 'CNGAOXIN419BAO', 'Alex @ JFK'),
      ('CNWUHXIX12WUH', 'CNWUHXIX32WUH', 'Alex @ JFK'),
      ('CNBAONUO3BAO', 'CNBAONUO7BAO', 'Alex @ JFK'),
      ('CNJUNINC1LIS', 'CNJUNINC2LIS', 'Alex @ JFK'),
      ('CNZHAXIA128ZHA', 'CNZHAXIA1542ZHA', 'Alex @ JFK'),
      ('CNGUASHU407GUA', 'CNGUASHU408GUA', 'Alex @ JFK'),
      ('CNQINCIT301QIN', 'CNQINCIT3014QIN', 'Alex @ JFK'),
      ('CNFOSCOL02FOS', 'CNFOSCOL553FOS', 'Alex @ JFK'),
      ('CNNANYAQ002NAN', 'CNNANYAQ3NAN', 'Alex @ JFK'),
      ('CNGUAMIM067GUA', 'CNGUAMIM67GUA', 'Alex @ JFK'),
      ('CNQINSHO0421QUA', 'CNQINSHO421QUA', 'Alex @ JFK'),
      ('CNHUAMEI002GUA', 'CNHUAMEI21GUA', 'Alex @ JFK'),
      ('CNJIULIT109JIU', 'CNJIULIT1092JIU', 'Alex @ JFK'),
      ('CNDONCHI4018JIN', 'CNDONCHI401JIN', 'Alex @ JFK'),
      ('CNGAOCIT0114BAO', 'CNGAOCIT9901BAO', 'Alex @ JFK'),
      ('CNGUASEA24GUA', 'CNGUASEA245GUA', 'Alex @ JFK'),
      ('CNGUAZHI286GUA', 'CNGUAZHI995GUA', 'Alex @ JFK'),
      ('CNJIAWEN1HAN', 'CNJIAWEN215HAN', 'Alex @ JFK'),
      ('CNBAOMEI0328BAO', 'CNBAOMEI328BAO', 'Alex @ JFK'),
      ('CNGUASIN275GUA', 'CNGUASIN27GUA', 'Alex @ JFK'),
      ('CNDONZHU938JIN', 'CNDONZHU93JIN', 'Alex @ JFK'),
      ('CNZHECAI134ZHE', 'CNZHECAI13ZHE', 'Alex @ JFK'),
      ('CNGAOWEI0233BAO', 'CNGAOWEI233BAO', 'Alex @ JFK'),
      ('CNBAOHOU01BAO', 'CNBAOHOU1BAO', 'Alex @ JFK'),
      ('CNXIAECO02FOS', 'CNXIAECO28FOS', 'Alex @ JFK'),
      ('CNGUABOP119GUA', 'CNGUABOP9915GUA', 'Alex @ JFK'),
      ('CNGUAXIO701GUA', 'CNGUAXIO929GUA', 'Alex @ JFK'),
      ('CNFOSBEI707FOS', 'CNFOSBEI708FOS', 'Alex @ JFK'),
      ('CNYANJIN18XUC', 'CNYANJIN8XUC', 'Alex @ JFK'),
      ('CNHUASHE5HUA', 'CNHUASHE589HUA', 'Alex @ JFK'),
      ('CNYIWKOU307JIN', 'CNYIWKOU1611JIN', 'Alex @ JFK'),
      ('CNYUECOU083ANQ', 'CNYUECOU83ANQ', 'Alex @ JFK'),
      ('CNYIWQIAJIN', 'CNYIWQIA613JIN', 'Alex @ JFK'),
      ('CNGAOXIN0608BAO', 'CNGAOXIN6081BAO', 'Alex @ JFK'),
      ('CNWUHBOY08WUH', 'CNWUHBOY167WUH', 'Alex @ JFK'),
      ('CNYIWJIN0434JIN', 'CNYIWJIN4348JIN', 'Alex @ JFK'),
      ('CNFOSJIA02FOS', 'CNFOSJIA9902FOS', 'Alex @ JFK'),
      ('CNUS518JIN', 'CNUSCCRO518JIN', 'Alex @ JFK'),
      ('CNGAOXIN0402BAO', 'CNGAOXIN402BAO', 'Alex @ JFK'),
      ('CNLEIDIG1046SHE', 'CNLEIDIG46SHE', 'Alex @ JFK'),
      ('CNGUAWEI0064GUA', 'CNGUAWEI434GUA', 'Alex @ JFK'),
      ('CNGONXIN064JIU', 'CNGONXIN64JIU', 'Alex @ JFK'),
      ('CNGAOXIN0101BAO', 'CNGAOXIN101BAO', 'Alex @ JFK'),
      ('CNGAOYUE0301BAO', 'CNGAOYUE301BAO', 'Alex @ JFK'),
      ('CNGUADAN003GUA', 'CNGUADAN194GUA', 'Alex @ JFK'),
      ('CNBAODAL0108BAO', 'CNBAODAL108BAO', 'Alex @ JFK'),
      ('CNYINDEP03FOS', 'CNYINDEP17FOS', 'Alex @ JFK'),
      ('CNANQYIH083ANQ', 'CNANQYIH83ANQ', 'Alex @ JFK'),
      ('CNMINCOU029SHA', 'CNMINCOU1018SHA', 'Alex @ JFK'),
      ('CNGAOLIA0031BAO', 'CNGAOLIA3160BAO', 'Alex @ JFK'),
      ('CNHENBUF05ZHE', 'CNHENBUF592ZHE', 'Alex @ JFK'),
      ('CNSHASENSHA', 'CNSHASEN462SHA', 'Alex @ JFK'),
      ('CNCHAWAN32CHA', 'CNCHAWAN42CHA', 'Alex @ JFK'),
      ('CNDABDEP21ZHE', 'CNDABDEP26ZHE', 'Alex @ JFK'),
      ('CNGAOXIN0223BAO', 'CNGAOXIN223BAO', 'Alex @ JFK'),
      ('CNGUAGUL3GUA', 'CNGUAGUL334GUA', 'Alex @ JFK'),
      ('CNFOSYIR2FOS', 'CNFOSYIR130FOS', 'Alex @ JFK'),
      ('CNTAIJUY23TAI', 'CNTAIJUY32TAI', 'Alex @ JFK'),
      ('CNYIWKAN407JIN', 'CNYIWKAN655JIN', 'Alex @ JFK'),
      ('CNYIWWOY1JIN', 'CNYIWWOY6JIN', 'Alex @ JFK'),
      ('CNYIWMAG12JIN', 'CNYIWMAG27JIN', 'Alex @ JFK'),
      ('CNNANXUZ0178NAN', 'CNNANXUZ178NAN', 'Alex @ JFK'),
      ('CNZHUHAO101SHA', 'CNZHUHAO151SHA', 'Alex @ JFK'),
      ('CNQITYUN13QIT', 'CNQITYUN23QIT', 'Alex @ JFK'),
      ('CNSHIQIASHI', 'CNSHIQIA99SHI', 'Alex @ JFK'),
      ('CNSHEJIN', 'CNSHE9910JIN', 'Alex @ JFK'),
      ('CNYIWTUA89JIN', 'CNYIWTUA994JIN', 'Alex @ JFK'),
      ('CNYIWXUG1JIN', 'CNYIWXUG9JIN', 'Alex @ JFK'),
      ('CNFOSBEI01FOS', 'CNFOSBEI9901FOS', 'Alex @ JFK'),
      ('CNDONBUG2JIN', 'CNDONBUG7JIN', 'Alex @ JFK'),
      ('CNBAINEW031BAO', 'CNBAINEW733BAO', 'Alex @ JFK'),
      ('CNBAINEW007BAO', 'CNBAINEW351BAO', 'Alex @ JFK'),
      ('CNGUALIH210GUA', 'CNGUALIH287GUA', 'Alex @ JFK'),
      ('CNYIWCOO1577JIN', 'CNYIWCOO157JIN', 'Alex @ JFK'),
      ('CNGAOXIN0417BAO', 'CNGAOXIN531BAO', 'Alex @ JFK'),
      ('CNHEFDIE1022HEF', 'CNHEFDIE1188HEF', 'Alex @ JFK'),
      ('VNANBINBAC', 'VNBINBGBAC', 'Alex @ JFK'),
      ('CNNANMEIQUA', 'CNNANMEI99QUA', 'Alex @ JFK'),
      ('CNGUAYIB097GUA', 'CNGUAYIB196GUA', 'Alex @ JFK'),
      ('CNWENNIS15WEN', 'CNWENNIS9938WEN', 'Alex @ JFK'),
      ('CNYIWAIX588JIN', 'CNYIWAIX9930JIN', 'Alex @ JFK'),
      ('HKHONKON22YAU', 'HKHONKON98YAU', 'Alex @ JFK'),
      ('CNZHOHAN94ZHO', 'CNZHOHAN19ZHO', 'Alex @ JFK'),
      ('CNGUAYUQ903GUA', 'CNGUAYUQ23GUA', 'Alex @ JFK'),
      ('CNZHUJIUSHA', 'CNZHUJIU99SHA', 'Alex @ JFK'),
      ('CNWANHAN3CHA', 'CNWANHAN7CHA', 'Alex @ JFK'),
      ('CNYIWSHI0212JIN', 'CNYIWSHI2120JIN', 'Alex @ JFK'),
      ('CNGUARUN1018GUA', 'CNGUARUN353GUA', 'Alex @ JFK'),
      ('CNJINCOM0341BAO', 'CNJINCOM341BAO', 'Alex @ JFK'),
      ('CNFOSAIR2FOS', 'CNFOSAIR3FOS', 'Alex @ JFK'),
      ('CNYIWJUC2JIN', 'CNYIWJUC874JIN', 'Alex @ JFK'),
      ('CNYIWCHO0555JIN', 'CNYIWCHO555JIN', 'Alex @ JFK'),
      ('CNWUJLIX1SUZ', 'CNWUJLIX5SUZ', 'Alex @ JFK'),
      ('CNHEFXIN1211HEF', 'CNHEFXIN1223HEF', 'Alex @ JFK'),
      ('HKSUNCOLKWU', 'HKSUNCOKWU', 'Alex @ JFK'),
      ('CNMENSEL4HAI', 'CNMENSEL6HAI', 'Alex @ JFK'),
      ('CNXIAMIS007ZHO', 'CNXIAMIS7ZHO', 'Alex @ JFK'),
      ('CNYIWHEQ1JIN', 'CNYIWHEQ8JIN', 'Alex @ JFK'),
      ('CNXIXNEW0103XIA', 'CNXIXNEW2062XIA', 'Alex @ JFK'),
      ('VNMINVIEHAI', 'VNMINVIE2845HAI', 'Alex @ JFK'),
      ('VNHUNFUN21DAK', 'VNHUNFUN24DAK', 'Alex @ JFK'),
      ('CNBAINEW0001BAO', 'CNBAINEW1BAO', 'Alex @ JFK'),
      ('CNYIWRON0011JIN', 'CNYIWRON399JIN', 'Alex @ JFK'),
      ('CNDONFUY61JIN', 'CNDONFUYJIN', 'Alex @ JFK'),
      ('CNFOSQIJ01FOS', 'CNFOSQIJ6FOS', 'Alex @ JFK'),
      ('CNDONDUR2JIN', 'CNDONDUR5JIN', 'Alex @ JFK'),
      ('CNGAOXIN0427BAO', 'CNGAOXIN427BAO', 'Alex @ JFK'),
      ('CNYIWJIX302JIN', 'CNYIWJIX715JIN', 'Alex @ JFK'),
      ('CNSUZFUM5SUZ', 'CNSUZFUM9SUZ', 'Alex @ JFK'),
      ('CNNANGAL1558NAN', 'CNNANGAL479NAN', 'Alex @ JFK'),
      ('CNZHEZHE092ZHE', 'CNZHEZHE92ZHE', 'Alex @ JFK'),
      ('CNYIDPIN23YIC', 'CNYIDPIN3YIC', 'Alex @ JFK'),
      ('CNGUAMAN614GUA', 'CNGUAMAN680GUA', 'Alex @ JFK'),
      ('CNGUASHE010GUA', 'CNGUASHE611GUA', 'Alex @ JFK'),
      ('CNGUAXIK204GUA', 'CNGUAXIK238GUA', 'Alex @ JFK'),
      ('CNSHICOU13CHI', 'CNSHICOU15CHI', 'Alex @ JFK'),
      ('CNDONDIS2KUN', 'CNDONDIS8KUN', 'Alex @ JFK'),
      ('CNGAOLIA0072BAO', 'CNGAOLIA7205BAO', 'Alex @ JFK'),
      ('CNDONMOU29JIN', 'CNDONMOU30JIN', 'Alex @ JFK'),
      ('CNSHESHE182SHE', 'CNSHESHE18SHE', 'Alex @ JFK'),
      ('CNHECART3002HAN', 'CNHECART1418HAN', 'Alex @ JFK'),
      ('CNBAOCHE3BAO', 'CNBAOCHE6BAO', 'Alex @ JFK'),
      ('CNMEETHE61FUZ', 'CNMEEBEA61FUZ', 'Alex @ JFK'),
      ('CNSHEMIL05SHE', 'CNSHEMIL847SHE', 'Alex @ JFK'),
      ('CNGUAOMA006GUA', 'CNGUAOMA123GUA', 'Alex @ JFK'),
      ('CNYIWNIT1JIN', 'CNYIWNIT8JIN', 'Alex @ JFK'),
      ('CNYIWKEZ2JIN', 'CNYIWKEZ3JIN', 'Alex @ JFK'),
      ('CNQINLAK606NAN', 'CNQINLAK888NAN', 'Alex @ JFK'),
      ('CNSHAQIN0096SHA', 'CNSHAQIN2816SHA', 'Alex @ JFK'),
      ('CNHANHOU4HAN', 'CNHANHOU308HAN', 'Alex @ JFK'),
      ('CNSHEQUZ201SHE', 'CNSHEQUZ273SHE', 'Alex @ JFK'),
      ('CNLINANJIN', 'CNLIN3831JIN', 'Alex @ JFK'),
      ('CNXIUCOU113JIU', 'CNXIUCOU154JIU', 'Alex @ JFK'),
      ('CNYUEREH4ANQ', 'CNYUEREH9ANQ', 'Alex @ JFK'),
      ('CNHANMIT0282HAN', 'CNHANMIT1399HAN', 'Alex @ JFK'),
      ('CNGAOXIN0327BAO', 'CNGAOXIN327BAO', 'Alex @ JFK'),
      ('CNYIWLAI1JIN', 'CNYIWLAI5JIN', 'Alex @ JFK'),
      ('CNYIWFUWJIN', 'CNYIWFUW18JIN', 'Alex @ JFK'),
      ('CNBAOVAL3BAO', 'CNBAOVAL7BAO', 'Alex @ JFK'),
      ('CNYIWXID708JIN', 'CNYIWXID788JIN', 'Alex @ JFK'),
      ('CNSHETRA08GUA', 'CNSHETRA8GUA', 'Alex @ JFK'),
      ('CNJIADIA102NAN', 'CNJIADIA326NAN', 'Alex @ JFK'),
      ('CNMIACOU2HAN', 'CNMIACOU9HAN', 'Alex @ JFK'),
      ('CNFUZGUL01FUZ', 'CNFUZGUL18FUZ', 'Alex @ JFK'),
      ('CNHANYUH0550HAN', 'CNHANYUH1399HAN', 'Alex @ JFK'),
      ('CNBAIXIN008BAO', 'CNBAIXIN8BAO', 'Alex @ JFK'),
      ('CNXINTEX570QIN', 'CNXINTEX70QIN', 'Alex @ JFK'),
      ('CNYIWDUC3JIN', 'CNYIWDUC9JIN', 'Alex @ JFK'),
      ('CNYIWPUY2JIN', 'CNYIWPUY8JIN', 'Alex @ JFK'),
      ('CNPUJJIA196JIN', 'CNPUJJIA19JIN', 'Alex @ JFK'),
      ('CNYIWNIA149JIN', 'CNYIWNIA14JIN', 'Alex @ JFK'),
      ('CNGUIBAO299GUI', 'CNGUIBAO29GUI', 'Alex @ JFK'),
      ('CNZHEGUA121ZHE', 'CNZHEGUA329ZHE', 'Alex @ JFK'),
      ('CNWUHNEW01WUH', 'CNWUHNEW58WUH', 'Alex @ JFK'),
      ('CNGUALON404GUA', 'CNGUALON665GUA', 'Alex @ JFK'),
      ('CNZHEMOY1ZHE', 'CNZHEMOY7ZHE', 'Alex @ JFK'),
      ('CNTIACHA0402TIA', 'CNTIACHA402TIA', 'Alex @ JFK'),
      ('CNBAOBAI001BAO', 'CNBAOBAI1BAO', 'Alex @ JFK'),
      ('CNTIAZHE108TIA', 'CNTIAZHE116TIA', 'Alex @ JFK'),
      ('CNTAIBORTAI', 'CNTAIBOR1TAI', 'Alex @ JFK'),
      ('CNZHUYIS102SHA', 'CNZHUYIS772SHA', 'Alex @ JFK'),
      ('CNSHEULU0070SHE', 'CNSHEULU7012SHE', 'Alex @ JFK'),
      ('CNSHALAN1700SHA', 'CNSHALAN170SHA', 'Alex @ JFK'),
      ('CNNANHAO1409NAN', 'CNNANHAO3399NAN', 'Alex @ JFK'),
      ('CNDONSHI1187DON', 'CNDONSHI101DON', 'Alex @ JFK'),
      ('CNBAINEW028BAO', 'CNBAINEW28BAO', 'Alex @ JFK'),
      ('CNSUZIND145SUZ', 'CNSUZIND199SUZ', 'Alex @ JFK'),
      ('CNGUAMUY0328GUA', 'CNGUAMUY328GUA', 'Alex @ JFK'),
      ('CN**1212JIN', 'CNZHAZHE1212JIN', 'Alex @ JFK'),
      ('CNSUSHUI14HUI', 'CNSUSHUI15HUI', 'Alex @ JFK'),
      ('CNYIWSU202JIN', 'CNYIWSU508JIN', 'Alex @ JFK'),
      ('CNJINHUI2QUA', 'CNJINHUI3QUA', 'Alex @ JFK'),
      ('CNGAOXIN0141BAO', 'CNGAOXIN1411BAO', 'Alex @ JFK'),
      ('CNFOSDEC026FOS', 'CNFOSDEC38FOS', 'Alex @ JFK'),
      ('CNCENWEI1WUZ', 'CNCENWEI2WUZ', 'Alex @ JFK'),
      ('CNDONYIT1JIN', 'CNDONYIT5JIN', 'Alex @ JFK'),
      ('CNZHUYUA126ZHU', 'CNZHUYUA216ZHU', 'Alex @ JFK'),
      ('CNSHEKAI012SHE', 'CNSHEKAI12SHE', 'Alex @ JFK'),
      ('CNSHEXIN053SHE', 'CNSHEXIN53SHE', 'Alex @ JFK'),
      ('CNGUAXIJ0278GUA', 'CNGUAXIJ278GUA', 'Alex @ JFK'),
      ('CNGUAQIA043GUA', 'CNGUAQIA222GUA', 'Alex @ JFK'),
      ('CNWUHWEI02WUH', 'CNWUHWEI58WUH', 'Alex @ JFK'),
      ('CNYUNTRA03FOS', 'CNYUNTRA12FOS', 'Alex @ JFK'),
      ('CNFOSANN1FOS', 'CNFOSANN8FOS', 'Alex @ JFK'),
      ('CNFOSSUM1FOS', 'CNFOSSUM4FOS', 'Alex @ JFK'),
      ('CNLEFDEP023LUO', 'CNLEFDEP23LUO', 'Alex @ JFK'),
      ('CNDONJUN116JIN', 'CNDONJUN116JIN', 'Alex @ JFK'),
      ('CNGUASHI386GUA', 'CNGUASHI445GUA', 'Alex @ JFK'),
      ('CNWUHYOU01WUH', 'CNWUHYOU77WUH', 'Alex @ JFK'),
      ('CNSHEMAI006SHE', 'CNSHEMAI375SHE', 'Alex @ JFK'),
      ('CNYIWPUM13JIN', 'CNYIWPUM36JIN', 'Alex @ JFK'),
      ('CNYIWBOD1JIN', 'CNYIWBOD5JIN', 'Alex @ JFK'),
      ('CNPUJQIA2JIN', 'CNPUJQIA7JIN', 'Alex @ JFK'),
      ('CNBEIMIN0319BEI', 'CNBEIMIN319BEI', 'Alex @ JFK'),
      ('CNWUHDON306WUH', 'CNWUHDON450WUH', 'Alex @ JFK'),
      ('CNGUAYIN614GUA', 'CNGUAYIN680GUA', 'Alex @ JFK'),
      ('CNYIWLUS407JIN', 'CNYIWLUS715JIN', 'Alex @ JFK'),
      ('CNYIWINT2JIN', 'CNYIWINT3JIN', 'Alex @ JFK'),
      ('CNYIWGAI2JIN', 'CNYIWGAI9JIN', 'Alex @ JFK'),
      ('CNXIAYIR104XIA', 'CNXIAYIR159XIA', 'Alex @ JFK'),
      ('CNBAOHUI0209BAO', 'CNBAOHUI209BAO', 'Alex @ JFK'),
      ('CNBAOBAI060BAO', 'CNBAOBAI60BAO', 'Alex @ JFK'),
      ('CNPUJTUO201JIN', 'CNPUJTUO371JIN', 'Alex @ JFK'),
      ('CNTOUA302JIN', 'CNTOUTRA302JIN', 'Alex @ JFK'),
      ('CNYIWKUO401JIN', 'CNYIWKUO606JIN', 'Alex @ JFK'),
      ('CNYIWXUA177JIN', 'CNYIWXUA405JIN', 'Alex @ JFK'),
      ('CNSHUCOU09SUQ', 'CNSHUCOU20SUQ', 'Alex @ JFK'),
      ('CNYIWNAN758JIN', 'CNYIWNAN931JIN', 'Alex @ JFK'),
      ('CNCHAWAN0800CHA', 'CNCHAWAN8006CHA', 'Alex @ JFK'),
      ('CNDINSUP05GUA', 'CNDINSUP8GUA', 'Alex @ JFK'),
      ('CNGAOXIN0403BAO', 'CNGAOXIN403BAO', 'Alex @ JFK'),
      ('CNYIWFUX88JIN', 'CNYIWFUX8JIN', 'Alex @ JFK'),
      ('CNYIWFUX3JIN', 'CNYIWFUX9JIN', 'Alex @ JFK'),
      ('CNHEBQIB03HEB', 'CNHEBQIB4HEB', 'Alex @ JFK'),
      ('CNZHEZHU026ZHE', 'CNZHEZHU52ZHE', 'Alex @ JFK'),
      ('CNSHIHUI210QUA', 'CNSHIHUI500QUA', 'Alex @ JFK'),
      ('CNPOYCOU697SHA', 'CNPOYCOU69SHA', 'Alex @ JFK'),
      ('CNGUA5035GUANGZ', 'CNGUAYA503GUA', 'Alex @ JFK'),
      ('TRTEKTEK723IST', 'TRTEKTEK72IST', 'Alex @ JFK'),
      ('CNTIAHUA002TIA', 'CNTIAHUA6TIA', 'Alex @ JFK'),
      ('CNDONMAN0198DON', 'CNDONMAN409DON', 'Alex @ JFK'),
      ('CNGUAXUA6789GUA', 'CNGUAXUA106GUA', 'Alex @ JFK'),
      ('CNGUAYIS7410GUA', 'CNGUAYIS103GUA', 'Alex @ JFK'),
      ('CNXINCHE2188HUL', 'CNXINCHE2188HUL', 'Alex @ JFK'),
      ('CNSHEDEP0468EZH', 'CNSHEDEP468EZH', 'Alex @ JFK'),
      ('CNYIWBIN0441JIN', 'CNYIWBIN4417JIN', 'Alex @ JFK'),
      ('CNYIWPAS27JIN', 'CNYIWPAS33JIN', 'Alex @ JFK'),
      ('CNSUZYIW5SUZ', 'CNSUZYIW995SUZ', 'Alex @ JFK'),
      ('CNGUAYIH018LIA', 'CNGUAYIH18LIA', 'Alex @ JFK'),
      ('CNYIWFUX606JIN', 'CNYIWFUX715JIN', 'Alex @ JFK'),
      ('CNYIWENR4JIN', 'CNYIWENR9JIN', 'Alex @ JFK'),
      ('CNNANLUO048NAN', 'CNNANLUO48NAN', 'Alex @ JFK'),
      ('CNFOSCOO08FOS', 'CNFOSCOO8FOS', 'Alex @ JFK'),
      ('CNFOSYAD01FOS', 'CNFOSYAD4FOS', 'Alex @ JFK'),
      ('CNSHEBEA2FOS', 'CNSHEBEA8FOS', 'Alex @ JFK'),
      ('CNGUABAN0806DON', 'CNGUABAN806DON', 'Alex @ JFK'),
      ('CNSHIWAL202QUA', 'CNSHIWAL237QUA', 'Alex @ JFK'),
      ('CNQINDIS1NAN', 'CNQINDIS3NAN', 'Alex @ JFK'),
      ('CNGUAYAO0211GUA', 'CNGUAYAO211GUA', 'Alex @ JFK'),
      ('CNYIWZIL103JIN', 'CNYIWZIL718JIN', 'Alex @ JFK'),
      ('CNSHAYIQ011RIZ', 'CNSHAYIQ11RIZ', 'Alex @ JFK'),
      ('CNGUANUA2GUA', 'CNGUANUA7GUA', 'Alex @ JFK'),
      ('CNYIWBET3JIN', 'CNYIWBET4JIN', 'Alex @ JFK'),
      ('CNBAIXIN007BAO', 'CNBAIXIN7BAO', 'Alex @ JFK'),
      ('CNQINQIY1QIN', 'CNQINQIY3QIN', 'Alex @ JFK'),
      ('CNXIACIT0201XIA', 'CNXIACIT2010XIA', 'Alex @ JFK'),
      ('CNGAOXIN0444BAO', 'CNGAOXIN4441BAO', 'Alex @ JFK'),
      ('CNPUJZHEJIN', 'CNPUJZHE99JIN', 'Alex @ JFK'),
      ('CNORCGAR063GUA', 'CNORCGAR302GUA', 'Alex @ JFK'),
      ('CNSUZTAI5SUZ', 'CNSUZTAI9SUZ', 'Alex @ JFK'),
      ('CNTAIYUN025TAI', 'CNTAIYUN25TAI', 'Alex @ JFK')
)
INSERT INTO midmap.mid_aliases(bad_mid, good_manufacturer_id, created_by)
SELECT btrim(upper(s.bad_mid)),
       cm.id,
       NULLIF(btrim(s.created_by), '')
FROM stg s
JOIN midmap.canonical_manufacturers cm ON cm.good_mid = btrim(upper(s.good_mid))
WHERE NULLIF(btrim(s.bad_mid), '') IS NOT NULL
ON CONFLICT (bad_mid) DO UPDATE
  SET good_manufacturer_id = EXCLUDED.good_manufacturer_id;

COMMIT;